# Generated by Django 5.1.4 on 2025-01-07 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("location", models.URLField()),
                ("bedrooms", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("land", "Land"),
                            ("house", "House"),
                            ("office", "Office"),
                            ("shop", "Shop"),
                            ("godown", "Godown"),
                            ("villa", "Villa"),
                            ("loft", "Loft"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sale_or_rent",
                    models.CharField(
                        choices=[("sale", "Sale"), ("rent", "Rent")], max_length=50
                    ),
                ),
                ("images", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
