# Generated by Django 5.1.4 on 2025-01-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_remove_property_images_propertyimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_images/"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_images/"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_images/"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="image4",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_images/"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="image5",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_images/"
            ),
        ),
    ]
