# Generated by Django 5.1.4 on 2025-01-08 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0007_property_is_booked_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="booking",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
