# Generated by Django 5.1.5 on 2025-01-18 12:42

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Realtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="realtors/%Y/%m/%d/", verbose_name="Photo"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_mvp",
                    models.BooleanField(default=False, verbose_name="MVP Status"),
                ),
                (
                    "hire_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Hire Date"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Property Title"),
                ),
                ("description", models.TextField(verbose_name="Property Description")),
                ("map_link", models.TextField(verbose_name="Property Map")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("booked", "Booked"),
                            ("sold", "Sold"),
                            ("rented", "Rented"),
                            ("off_market", "Off Market"),
                            ("unapproved", "Unapproved"),
                        ],
                        max_length=20,
                        verbose_name="Property Status",
                    ),
                ),
                ("province", models.CharField(max_length=20, verbose_name="Province")),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("bhojpur", "Bhojpur"),
                            ("dhankuta", "Dhankuta"),
                            ("ilam", "Ilam"),
                            ("jhapa", "Jhapa"),
                            ("khotang", "Khotang"),
                            ("morang", "Morang"),
                            ("okhaldhunga", "Okhaldhunga"),
                            ("panchthar", "Panchthar"),
                            ("sankhuwasabha", "Sankhuwasabha"),
                            ("solukhumbu", "Solukhumbu"),
                            ("sunsari", "Sunsari"),
                            ("taplejung", "Taplejung"),
                            ("terhathum", "Terhathum"),
                            ("udayapur", "Udayapur"),
                            ("bara", "Bara"),
                            ("dhanusha", "Dhanusha"),
                            ("mahottari", "Mahottari"),
                            ("parsa", "Parsa"),
                            ("rautahat", "Rautahat"),
                            ("saptari", "Saptari"),
                            ("sarlahi", "Sarlahi"),
                            ("siraha", "Siraha"),
                            ("bhaktapur", "Bhaktapur"),
                            ("chitwan", "Chitwan"),
                            ("dhading", "Dhading"),
                            ("dolakha", "Dolakha"),
                            ("kathmandu", "Kathmandu"),
                            ("kavrepalanchok", "Kavrepalanchok"),
                            ("lalitpur", "Lalitpur"),
                            ("makwanpur", "Makwanpur"),
                            ("nuwakot", "Nuwakot"),
                            ("ramechhap", "Ramechhap"),
                            ("rasuwa", "Rasuwa"),
                            ("sindhuli", "Sindhuli"),
                            ("sindhupalchok", "Sindhupalchok"),
                            ("baglung", "Baglung"),
                            ("gorkha", "Gorkha"),
                            ("kaski", "Kaski"),
                            ("lamjung", "Lamjung"),
                            ("manang", "Manang"),
                            ("mustang", "Mustang"),
                            ("myagdi", "Myagdi"),
                            ("nawalpur", "Nawalpur"),
                            ("parbat", "Parbat"),
                            ("syangja", "Syangja"),
                            ("tanahun", "Tanahun"),
                            ("arghakhanchi", "Arghakhanchi"),
                            ("banke", "Banke"),
                            ("bardiya", "Bardiya"),
                            ("dang", "Dang"),
                            ("gulmi", "Gulmi"),
                            ("kapilvastu", "Kapilvastu"),
                            ("palpa", "Palpa"),
                            ("parasi", "Parasi"),
                            ("pyuthan", "Pyuthan"),
                            ("rolpa", "Rolpa"),
                            ("rupandehi", "Rupandehi"),
                            ("dailekh", "Dailekh"),
                            ("dolpa", "Dolpa"),
                            ("humla", "Humla"),
                            ("jumla", "Jumla"),
                            ("kalikot", "Kalikot"),
                            ("mugu", "Mugu"),
                            ("rukum_west", "Rukum West"),
                            ("salyan", "Salyan"),
                            ("surkhet", "Surkhet"),
                            ("achham", "Achham"),
                            ("baitadi", "Baitadi"),
                            ("bajhang", "Bajhang"),
                            ("bajura", "Bajura"),
                            ("dadeldhura", "Dadeldhura"),
                            ("darchula", "Darchula"),
                            ("kanchanpur", "Kanchanpur"),
                            ("kailali", "Kailali"),
                            ("doti", "Doti"),
                        ],
                        max_length=50,
                        verbose_name="District",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                ("bed", models.IntegerField(verbose_name="Number of Bedrooms")),
                ("bath", models.IntegerField(verbose_name="Number of Bathrooms")),
                (
                    "area",
                    models.IntegerField(
                        help_text="Area in square feet", verbose_name="Area (sq ft)"
                    ),
                ),
                (
                    "plot_number",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Lot size in acres",
                        max_digits=10,
                        verbose_name="Plot Number",
                    ),
                ),
                (
                    "photo_main",
                    models.ImageField(
                        upload_to="photos/%Y/%m/%d/", verbose_name="Main Photo"
                    ),
                ),
                (
                    "photo_1",
                    models.ImageField(
                        blank=True, upload_to="photos/%Y/%m/%d/", verbose_name="Photo 1"
                    ),
                ),
                (
                    "photo_2",
                    models.ImageField(
                        blank=True, upload_to="photos/%Y/%m/%d/", verbose_name="Photo 2"
                    ),
                ),
                (
                    "photo_3",
                    models.ImageField(
                        blank=True, upload_to="photos/%Y/%m/%d/", verbose_name="Photo 3"
                    ),
                ),
                (
                    "photo_4",
                    models.ImageField(
                        blank=True, upload_to="photos/%Y/%m/%d/", verbose_name="Photo 4"
                    ),
                ),
                (
                    "photo_5",
                    models.ImageField(
                        blank=True, upload_to="photos/%Y/%m/%d/", verbose_name="Photo 5"
                    ),
                ),
                (
                    "sale_or_rent",
                    models.CharField(
                        choices=[("sale", "For Sale"), ("rent", "For Rent")],
                        max_length=4,
                        verbose_name="Sale or Rent",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("house", "House"),
                            ("apartment", "Apartment"),
                            ("condo", "Condo"),
                            ("land", "Land"),
                        ],
                        max_length=20,
                        verbose_name="Property Type",
                    ),
                ),
                ("year_built", models.IntegerField(verbose_name="Year Built")),
                (
                    "total_floors",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Floors"
                    ),
                ),
                (
                    "floor_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Applicable for apartments or multi-story buildings",
                        null=True,
                        verbose_name="Floor Number",
                    ),
                ),
                (
                    "amenities",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("garage", "Garage"),
                            ("pool", "Pool"),
                            ("fireplace", "Fireplace"),
                        ],
                        max_length=21,
                        verbose_name="Amenities",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        choices=[("featured", "Featured"), ("hot_deal", "Hot Deal")],
                        max_length=20,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "documents",
                    models.FileField(
                        blank=True,
                        upload_to="documents/%Y/%m/%d/",
                        verbose_name="Documents",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "added_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date Added"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "realtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="property.realtor",
                        verbose_name="Realtor",
                    ),
                ),
            ],
        ),
    ]
