# Generated by Django 5.1.5 on 2025-01-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0005_alter_property_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
