# Generated by Django 5.1.5 on 2025-01-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0006_alter_property_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="plot_number",
            field=models.IntegerField(
                help_text="Plot number", verbose_name="Plot Number"
            ),
        ),
    ]
