# Generated by Django 5.1.5 on 2025-01-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0007_alter_property_plot_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="province",
            field=models.CharField(
                choices=[
                    ("province1", "Province 1"),
                    ("madhesh_pradesh", "Madhesh Pradesh"),
                    ("bagmati", "Bagmati Province"),
                    ("gandaki", "Gandaki"),
                    ("lumbini", "Lumbini"),
                    ("karnali", "Karnali"),
                    ("sudurpaschim", "Sudurpaschim"),
                ],
                max_length=50,
                verbose_name="Province",
            ),
        ),
    ]
