# Generated by Django 5.1.5 on 2025-01-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0008_alter_property_province"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="amenities",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Amenities"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="district",
            field=models.CharField(max_length=50, verbose_name="District"),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(max_length=20, verbose_name="Property Type"),
        ),
        migrations.AlterField(
            model_name="property",
            name="province",
            field=models.CharField(max_length=50, verbose_name="Province"),
        ),
        migrations.AlterField(
            model_name="property",
            name="sale_or_rent",
            field=models.CharField(max_length=4, verbose_name="Sale or Rent"),
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(max_length=20, verbose_name="Property Status"),
        ),
        migrations.AlterField(
            model_name="property",
            name="tags",
            field=models.CharField(blank=True, max_length=20, verbose_name="Tags"),
        ),
    ]
