# Generated by Django 5.1.5 on 2025-01-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0009_alter_property_amenities_alter_property_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
