# Generated by Django 5.1.5 on 2025-01-18 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cement", "Cement Supplier"),
                            ("steel", "Steel Supplier"),
                            ("electrical", "Electrical Supplier"),
                            ("manpower", "Manpower Supplier"),
                            ("plumbing", "Plumbing Supplier"),
                            ("paint", "Paint Supplier"),
                            ("tiles", "Tiles Supplier"),
                            ("wood", "Wood Supplier"),
                            ("glass", "Glass Supplier"),
                            ("furniture", "Furniture Supplier"),
                            ("iot", "IOT Technology"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("phone_number", models.CharField(max_length=20)),
                ("maplink", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.FloatField()),
                ("quantity_unit", models.CharField(max_length=50)),
                ("price", models.FloatField()),
                ("price_unit", models.CharField(max_length=50)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="supplier.supplier",
                    ),
                ),
            ],
        ),
    ]
