# Generated by Django 5.1.5 on 2025-01-18 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0002_auto"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="material_image",
            field=models.ImageField(blank=True, upload_to="materials/%Y/%m/%d"),
        ),
        migrations.AddField(
            model_name="material",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("cement", "Cement"),
                    ("steel", "Steel"),
                    ("electrical", "Electrical"),
                    ("manpower", "Manpower"),
                    ("plumbing", "Plumbing"),
                    ("paint", "Paint"),
                    ("tiles", "Tiles"),
                    ("wood", "Wood"),
                    ("glass", "Glass"),
                    ("furniture", "Furniture"),
                    ("iot", "IOT Technology"),
                    ("other", "Other"),
                ],
                default=django.utils.timezone.now,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
