# Generated by Django 5.1.5 on 2025-01-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_complaint_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("booked", "Booked"),
                    ("sold", "Sold"),
                    ("rented", "Rented"),
                    ("off_market", "Off Market"),
                    ("unapproved", "Unapproved"),
                ],
                default="unapproved",
                max_length=20,
                verbose_name="Property Status",
            ),
        ),
    ]
