# Generated by Django 5.1.5 on 2025-01-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("engineering", "Engineering"),
                            ("measuring", "Measuring"),
                            ("legal", "Legal"),
                            ("plumbing", "Plumbing"),
                            ("electrical", "Electrical"),
                            ("landscaping", "Landscaping"),
                            ("painting", "Painting"),
                            ("security", "Security"),
                            ("moving", "Moving"),
                            ("renovation", "Renovation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("service_provider", models.CharField(max_length=255)),
                ("service_name", models.CharField(max_length=255)),
                ("service_charge", models.FloatField()),
                ("time_of_service", models.CharField(max_length=50)),
                ("service_description", models.TextField()),
                (
                    "service_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="services/%Y/%m/%d"
                    ),
                ),
            ],
        ),
    ]
