# Generated by Django 5.1.5 on 2025-01-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="provider_type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("company", "Company")],
                default="individual",
                max_length=20,
            ),
        ),
    ]
