# Generated by Django 5.1.5 on 2025-01-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_provider_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("engineering", "Engineering"),
                    ("measuring", "Measuring"),
                    ("legal", "Legal"),
                    ("plumbing", "Plumbing"),
                    ("electrical", "Electrical"),
                    ("landscaping", "Landscaping"),
                    ("painting", "Painting"),
                    ("security", "Security"),
                    ("moving", "Moving"),
                    ("renovation", "Renovation"),
                    ("cleaning", "Cleaning"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
