# Generated by Django 5.1.4 on 2025-01-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="images",
            field=models.ImageField(upload_to="property_images/"),
        ),
    ]
