# Generated by Django 5.1.5 on 2025-01-23 18:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_merge"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.JSONField(default=list),
        ),
    ]
