# Generated by Django 5.1.5 on 2025-01-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_auto_alter_user_role"),
        ("accounts", "0006_user_role"),
    ]

    operations = []
